### ISSUE TITLE
Unable to see the live website 

### ISSUE THREAD

**Issue by harsh-100** [mahak0711/flexstart#1]
- As a code enthuciast , i also want to see the live version of every application , you have added a link for your app (portfolio ) , it is not working at the moment . Then , what are you planning to make it live 🤔

Want to see the live version soon @mahak0711  
Thanks 🎉

**Comment by mahak0711** [comment]
Yes sir I'm working on it.But it's in html and css format and it's not
resolving through GitHub pages.

**Comment by mahak0711** [comment]
https://mahak0711.github.io/flexstart-main/

**Comment by harsh-100** [comment]
Good Work 🎉 @mahak
It is really looking amazing , 
> keep the show go on 😉
